//! SMT-LIB v2 import/export — Evident's portable HIR.
//!
//! Two functions:
//!   - `export(schema) -> String` walks an Evident `SchemaDecl` and
//!     emits SMT-LIB v2 text. The result is debuggable (claim name in
//!     a header comment, one decl/assertion per line) and consumable
//!     by any SMT solver.
//!   - `import(text) -> Vec<BodyItem>` parses SMT-LIB text into a
//!     list of Evident body items (Memberships + Constraints) ready
//!     to wrap in a `claim` decl.
//!
//! Scope is the constraint subset described in
//! `docs/design/smt-lib-as-ir.md`: primitive types, arithmetic +
//! comparison + logical ops, equality, quantifiers over Int ranges.
//! Datatypes, sequences, and records are out of scope for v1.
//!
//! Roundtrip is a lossy compilation — the exported SMT-LIB has no
//! claim composition, no subclaim names, no source comments. The
//! re-imported Evident program is one flat list of constraints,
//! semantically equivalent but textually unrecognizable.

use std::collections::{HashMap, HashSet};

use crate::ast::{BinOp, BodyItem, Expr, Mapping, Pins, SchemaDecl};

// ── Export: Evident AST → SMT-LIB text ──────────────────────────────────────

#[derive(Debug)]
pub struct ExportError(pub String);
impl std::fmt::Display for ExportError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result { write!(f, "{}", self.0) }
}
impl std::error::Error for ExportError {}

/// Translate one schema into a self-contained SMT-LIB v2 script.
///
/// `schemas` is the runtime's full type table — the exporter needs
/// it to flatten sub-record memberships (a `task ∈ Task` declaration
/// becomes one `declare-const` per leaf field, with Task's own
/// constraints replicated under the `task.` prefix).
///
/// Output: header comment naming the source claim, declarations,
/// assertions, then `(check-sat)` + `(get-model)` so piping into
/// `z3 -in` does the right thing.
///
/// Out-of-scope body items (passthrough, claim call, subclaim) and
/// types Evident knows about that SMT-LIB doesn't (Seq, Set, enums)
/// produce an `ExportError` naming the offending construct and
/// pointing at `docs/design/smt-lib-as-ir.md`.
pub fn export(
    schema: &SchemaDecl,
    schemas: &HashMap<String, SchemaDecl>,
) -> Result<String, ExportError> {
    let mut out = String::new();
    out.push_str(&format!("; Generated by Evident — claim: {}\n", schema.name));
    // Pick the SMT-LIB logic name that best covers the schema's
    // feature set. Z3 infers the logic from assertions, but
    // stricter solvers (Yices, CVC5) require an explicit
    // declaration. We pick the smallest logic that includes
    // everything the schema actually uses — broader is safer for
    // permissive solvers, narrower works on more solvers.
    let logic = select_logic(schema, schemas);
    out.push_str(&format!("(set-logic {logic})\n"));

    for item in &schema.body {
        emit_body_item(&mut out, item, schemas)?;
    }

    out.push_str("(check-sat)\n");
    out.push_str("(get-model)\n");
    Ok(out)
}

/// Pick the SMT-LIB logic name that covers everything the schema
/// uses. The matrix is small:
///
///   - Strings anywhere → "ALL" (only Z3 + CVC5 handle strings;
///     Yices doesn't support them at all, but ALL is the closest
///     standard name — strict solvers will reject the assertions
///     themselves with a clear "String sort not in this logic" message
///     rather than a misleading "logic unknown" one).
///   - Quantifiers + only Int → "LIA" (Linear Integer Arithmetic
///     with quantifiers; supported by Z3 and Yices).
///   - Quantifiers + Real (with or without Int) → "LRA" or "LIRA"
///     (LIRA isn't always supported; LRA is broader and works in Z3.
///     Yices may reject — strings + reals are the cross-solver
///     fragile zone).
///   - No quantifiers, no Real, no String → "ALL"
///     (quantifier-free in Yices's interpretation is fine).
///   - No quantifiers, Real involved → "QF_LIRA" (quantifier-free
///     mixed Int/Real arithmetic).
///
/// Designed so the COMMON case (Int + bool + arithmetic +/- bounded
/// quantifiers) lands on LIA, which both Z3 and Yices accept.
fn select_logic(schema: &SchemaDecl, schemas: &HashMap<String, SchemaDecl>) -> &'static str {
    let mut feat = Features::default();
    walk_schema_features(schema, schemas, &mut feat, &mut HashSet::new());
    match (feat.has_string, feat.has_real, feat.has_quantifier) {
        (true,  _,     _)     => "ALL",
        (false, true,  true)  => "LRA",      // mixed-arithmetic-with-quant: best effort
        (false, true,  false) => "QF_LIRA",
        (false, false, true)  => "LIA",
        (false, false, false) => "ALL",
    }
}

#[derive(Default)]
struct Features {
    has_quantifier: bool,
    has_real:       bool,
    has_string:     bool,
}

fn walk_schema_features(
    schema: &SchemaDecl,
    schemas: &HashMap<String, SchemaDecl>,
    feat: &mut Features,
    visited: &mut HashSet<String>,
) {
    if !visited.insert(schema.name.clone()) { return; }
    for item in &schema.body {
        match item {
            BodyItem::Membership { type_name, .. } => match type_name.as_str() {
                "Real" => feat.has_real = true,
                "String" => feat.has_string = true,
                "Int" | "Nat" | "Pos" | "Bool" => {}
                user => {
                    if let Some(sub) = schemas.get(user) {
                        walk_schema_features(sub, schemas, feat, visited);
                    }
                }
            },
            BodyItem::Constraint(e) => walk_expr_features(e, feat),
            _ => {}
        }
    }
}

fn walk_expr_features(e: &Expr, feat: &mut Features) {
    match e {
        Expr::Real(_) => feat.has_real = true,
        Expr::Str(_)  => feat.has_string = true,
        Expr::Forall(_, _, _) | Expr::Exists(_, _, _) => feat.has_quantifier = true,
        _ => {}
    }
    match e {
        Expr::Binary(_, l, r) | Expr::InExpr(l, r) | Expr::Range(l, r) | Expr::Index(l, r) => {
            walk_expr_features(l, feat);
            walk_expr_features(r, feat);
        }
        Expr::Not(i) | Expr::Cardinality(i) | Expr::Field(i, _) => walk_expr_features(i, feat),
        Expr::Ternary(c, a, b) => {
            walk_expr_features(c, feat);
            walk_expr_features(a, feat);
            walk_expr_features(b, feat);
        }
        Expr::Match(scr, arms) => {
            walk_expr_features(scr, feat);
            for a in arms { walk_expr_features(&a.body, feat); }
        }
        Expr::Forall(_, range, body) | Expr::Exists(_, range, body) => {
            walk_expr_features(range, feat);
            walk_expr_features(body, feat);
        }
        Expr::Call(_, args) | Expr::SetLit(args) | Expr::SeqLit(args) => {
            for a in args { walk_expr_features(a, feat); }
        }
        _ => {}
    }
}

fn emit_body_item(
    out: &mut String,
    item: &BodyItem,
    schemas: &HashMap<String, SchemaDecl>,
) -> Result<(), ExportError> {
    match item {
        BodyItem::Membership { name, type_name, pins } => {
            emit_membership(out, name, type_name, pins, schemas)?;
        }
        BodyItem::Constraint(e) => {
            let s = emit_expr(e)?;
            out.push_str(&format!("(assert {s})\n"));
        }
        BodyItem::Passthrough(name) => {
            return Err(ExportError(format!(
                "export: passthrough `..{name}` is not in scope — claim \
                 composition compiles away before constraint translation. \
                 Inline the body manually first."
            )));
        }
        BodyItem::ClaimCall { name, .. } => {
            return Err(ExportError(format!(
                "export: claim invocation `{name}(...)` is not in scope. \
                 Inline the body manually first."
            )));
        }
        BodyItem::SubclaimDecl(s) => {
            return Err(ExportError(format!(
                "export: subclaim `{}` is not in scope — only its parent's \
                 own constraints are exported.", s.name
            )));
        }
    }
    Ok(())
}

/// Emit declarations + assertions for one Membership. Primitives
/// emit a single `declare-const`; sub-record types recurse, emitting
/// one `declare-const` per leaf field plus the type's own
/// constraints rewritten under the parent's name. Pins (`x ∈
/// Type(v1, v2)`) become per-field equality assertions after the
/// declarations.
fn emit_membership(
    out: &mut String,
    name: &str,
    type_name: &str,
    pins: &Pins,
    schemas: &HashMap<String, SchemaDecl>,
) -> Result<(), ExportError> {
    if let Some((smt_sort, extra)) = primitive_sort(type_name) {
        out.push_str(&format!("(declare-const {name} {smt_sort})\n"));
        if let Some(a) = extra {
            out.push_str(&format!("(assert {})\n", a.replace("__VAR__", name)));
        }
        emit_pin_assertions(out, name, pins, schemas)?;
        return Ok(());
    }

    // Non-primitive: try the schemas table.
    let Some(type_schema) = schemas.get(type_name) else {
        return Err(ExportError(format!(
            "export: type `{type_name}` not in scope (only primitives \
             Int/Nat/Pos/Real/Bool/String + user-defined record types \
             with primitive leaf fields supported in v1)"
        )));
    };

    // Field names defined directly in this type's body. Used to
    // rewrite references in the type's own constraints.
    let direct_fields: HashSet<String> = type_schema.body.iter()
        .filter_map(|i| if let BodyItem::Membership { name, .. } = i {
            Some(name.clone())
        } else { None })
        .collect();

    // Pass 1: declarations for every leaf, recursively.
    for sub in &type_schema.body {
        if let BodyItem::Membership { name: f, type_name: ft, pins: fp } = sub {
            let dotted = format!("{name}.{f}");
            emit_membership(out, &dotted, ft, fp, schemas)?;
        }
    }
    // Pass 2: the type's own constraints, with bare references to
    // its fields rewritten under the parent's prefix
    // (`duration < deadline` becomes `task.duration < task.deadline`
    // when expanded under `task ∈ Task`).
    for sub in &type_schema.body {
        if let BodyItem::Constraint(e) = sub {
            let rewritten = rewrite_refs(e, &direct_fields, name);
            let s = emit_expr(&rewritten)?;
            out.push_str(&format!("(assert {s})\n"));
        }
    }
    // Pass 3: pins on the parent become per-field equalities.
    emit_pin_assertions(out, name, pins, schemas)?;

    Ok(())
}

/// Map an Evident primitive type name to its SMT-LIB sort + an
/// optional refinement assertion template. The template uses
/// `__VAR__` as a placeholder for the variable name; the caller
/// substitutes.
fn primitive_sort(t: &str) -> Option<(&'static str, Option<&'static str>)> {
    match t {
        "Int"    => Some(("Int", None)),
        "Nat"    => Some(("Int", Some("(>= __VAR__ 0)"))),
        "Pos"    => Some(("Int", Some("(> __VAR__ 0)"))),
        "Real"   => Some(("Real", None)),
        "Bool"   => Some(("Bool", None)),
        "String" => Some(("String", None)),
        _ => None,
    }
}

/// Convert a `Pins::Named` or `Pins::Positional` annotation into
/// per-field equality assertions. The parent's leaf names are
/// `<name>.<field>`; the pinned values get translated as ordinary
/// Evident expressions.
fn emit_pin_assertions(
    out: &mut String,
    name: &str,
    pins: &Pins,
    schemas: &HashMap<String, SchemaDecl>,
) -> Result<(), ExportError> {
    match pins {
        Pins::None => Ok(()),
        Pins::Named(maps) => {
            for Mapping { slot, value } in maps {
                let v = emit_expr(value)?;
                out.push_str(&format!("(assert (= {name}.{slot} {v}))\n"));
            }
            Ok(())
        }
        Pins::Positional(args) => {
            // Look up the type's field-declaration order. We need
            // the type to resolve positional pins, which means
            // walking the schema table. The Membership we're
            // pinning lives on the parent; its `type_name` was
            // already passed through to emit_membership. Re-derive
            // by sniffing `name`'s dotted children — but that's
            // hacky. Cleaner: have the caller pass `type_name` here
            // too. For now, error if Pins::Positional and recommend
            // using Named.
            let _ = args; let _ = schemas;
            Err(ExportError(format!(
                "export: positional pins on `{name}` not yet supported in v1; \
                 use named-pin form (`{name} ∈ Type(field1 ↦ v1, …)`) instead"
            )))
        }
    }
}

/// Walk an expression and rewrite bare references to any name in
/// `field_set` so they're prefixed with `parent.` Used to lift a
/// type's own constraints into a parent context. References that
/// don't match a field name pass through unchanged. Dotted
/// identifiers (`task.duration`) are matched on their root segment.
fn rewrite_refs(e: &Expr, field_set: &HashSet<String>, parent: &str) -> Expr {
    match e {
        Expr::Identifier(n) => {
            let root = n.split('.').next().unwrap_or(n);
            if field_set.contains(root) {
                Expr::Identifier(format!("{parent}.{n}"))
            } else {
                Expr::Identifier(n.clone())
            }
        }
        Expr::Binary(op, l, r) => Expr::Binary(
            op.clone(),
            Box::new(rewrite_refs(l, field_set, parent)),
            Box::new(rewrite_refs(r, field_set, parent)),
        ),
        Expr::Not(inner) => Expr::Not(Box::new(rewrite_refs(inner, field_set, parent))),
        Expr::Ternary(c, a, b) => Expr::Ternary(
            Box::new(rewrite_refs(c, field_set, parent)),
            Box::new(rewrite_refs(a, field_set, parent)),
            Box::new(rewrite_refs(b, field_set, parent)),
        ),
        Expr::Match(scr, arms) => Expr::Match(
            Box::new(rewrite_refs(scr, field_set, parent)),
            arms.iter().map(|a| crate::ast::MatchArm {
                pattern: a.pattern.clone(),
                body: Box::new(rewrite_refs(&a.body, field_set, parent)),
            }).collect(),
        ),
        Expr::Forall(binders, range, body) => Expr::Forall(
            binders.clone(),
            Box::new(rewrite_refs(range, field_set, parent)),
            Box::new(rewrite_refs(body, field_set, parent)),
        ),
        Expr::Exists(binders, range, body) => Expr::Exists(
            binders.clone(),
            Box::new(rewrite_refs(range, field_set, parent)),
            Box::new(rewrite_refs(body, field_set, parent)),
        ),
        Expr::Range(lo, hi) => Expr::Range(
            Box::new(rewrite_refs(lo, field_set, parent)),
            Box::new(rewrite_refs(hi, field_set, parent)),
        ),
        Expr::Call(name, args) => Expr::Call(
            name.clone(),
            args.iter().map(|a| rewrite_refs(a, field_set, parent)).collect(),
        ),
        Expr::Field(recv, f) => Expr::Field(
            Box::new(rewrite_refs(recv, field_set, parent)),
            f.clone(),
        ),
        Expr::Index(s, i) => Expr::Index(
            Box::new(rewrite_refs(s, field_set, parent)),
            Box::new(rewrite_refs(i, field_set, parent)),
        ),
        // Literals + collection forms don't contain refs to rewrite.
        other => other.clone(),
    }
}

fn emit_expr(e: &Expr) -> Result<String, ExportError> {
    Ok(match e {
        Expr::Int(n)  => n.to_string(),
        Expr::Real(r) => format_real(*r),
        Expr::Bool(b) => if *b { "true".into() } else { "false".into() },
        Expr::Str(s)  => format!("\"{}\"", s.replace('"', "\"\"")),
        Expr::Identifier(n) => n.clone(),
        Expr::Binary(op, lhs, rhs) => {
            let l = emit_expr(lhs)?;
            let r = emit_expr(rhs)?;
            let smt_op = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*", BinOp::Div => "div",
                BinOp::Lt => "<", BinOp::Le => "<=", BinOp::Gt => ">", BinOp::Ge => ">=",
                BinOp::Eq => "=", BinOp::Neq => "distinct",
                BinOp::And => "and", BinOp::Or => "or", BinOp::Implies => "=>",
                BinOp::Concat => "str.++",
            };
            format!("({smt_op} {l} {r})")
        }
        Expr::Not(inner) => format!("(not {})", emit_expr(inner)?),
        Expr::Ternary(c, a, b) => format!("(ite {} {} {})",
            emit_expr(c)?, emit_expr(a)?, emit_expr(b)?),
        Expr::Match(_, _) => return Err(ExportError(
            "match expressions not yet supported in SMT-LIB export".into())),
        Expr::Forall(binders, range, body) => {
            let (var, sort, low, high) = parse_int_range(binders, range)?;
            let body_s = emit_expr(body)?;
            format!(
                "(forall (({var} {sort})) (=> (and (>= {var} {low}) (<= {var} {high})) {body_s}))"
            )
        }
        Expr::Exists(binders, range, body) => {
            let (var, sort, low, high) = parse_int_range(binders, range)?;
            let body_s = emit_expr(body)?;
            format!(
                "(exists (({var} {sort})) (and (>= {var} {low}) (<= {var} {high}) {body_s}))"
            )
        }
        Expr::Call(name, _) => return Err(ExportError(format!(
            "export: function call `{name}(...)` is not in scope (no \
             user-defined functions in v1)"
        ))),
        Expr::SetLit(_) => return Err(ExportError(
            "export: set literals not in scope (Sets aren't mapped yet)".into())),
        Expr::SeqLit(_) => return Err(ExportError(
            "export: sequence literals not in scope".into())),
        Expr::Range(_, _) => return Err(ExportError(
            "export: bare range expressions only meaningful inside ∀/∃".into())),
        Expr::InExpr(_, _) => return Err(ExportError(
            "export: membership not in scope (sets aren't mapped yet)".into())),
        Expr::Cardinality(_) | Expr::Index(_, _) | Expr::Field(_, _) =>
            return Err(ExportError(format!(
                "export: composite-type expression not in scope: {e:?}"))),
    })
}

/// Parse a quantifier binding + range into (var, sort, low, high).
/// Only `∀ x ∈ {lo..hi}` shape is supported in v1 — no tuple binders,
/// no non-Int ranges.
fn parse_int_range(binders: &[String], range: &Expr)
    -> Result<(String, &'static str, String, String), ExportError>
{
    if binders.len() != 1 {
        return Err(ExportError(format!(
            "export: only single-binder ∀/∃ supported in v1, got {} binders",
            binders.len()
        )));
    }
    let var = binders[0].clone();
    let Expr::Range(lo, hi) = range else {
        return Err(ExportError(
            "export: ∀/∃ range must be a literal `{lo..hi}` integer range".into()));
    };
    let lo_s = emit_expr(lo)?;
    let hi_s = emit_expr(hi)?;
    Ok((var, "Int", lo_s, hi_s))
}

fn format_real(r: f64) -> String {
    let s = r.to_string();
    if s.contains('.') || s.contains('e') || s.contains('E') { s }
    else { format!("{s}.0") }
}

// ── Import: SMT-LIB text → Evident AST ──────────────────────────────────────

#[derive(Debug)]
pub struct ImportError(pub String);
impl std::fmt::Display for ImportError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result { write!(f, "{}", self.0) }
}
impl std::error::Error for ImportError {}

/// Parse SMT-LIB text into a list of Evident body items.
///
/// Solver directives (`(set-option …)`, `(set-info …)`, `(check-sat)`,
/// `(get-model)`, `(exit)`) are silently ignored — they're commands
/// to a solver, not constraints.
///
/// `(declare-const x T)` and `(declare-fun x () T)` (zero-arg fun)
/// both produce Memberships. Higher-arity `declare-fun` errors out.
///
/// `(assert e)` produces a Constraint after recursively translating
/// the s-expression body to an Evident `Expr`.
pub fn import(src: &str) -> Result<Vec<BodyItem>, ImportError> {
    let toks = tokenize(src)?;
    let forms = parse_top_level(&toks)?;
    let mut out = Vec::new();
    for form in forms {
        match form_to_body_item(&form)? {
            Some(item) => out.push(item),
            None => {} // ignored solver directive
        }
    }
    Ok(out)
}

#[derive(Debug, Clone)]
enum Sexp {
    Atom(String),
    List(Vec<Sexp>),
}

fn tokenize(src: &str) -> Result<Vec<String>, ImportError> {
    let mut out = Vec::new();
    let bytes = src.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        match b {
            b';' => {
                // Comment to EOL.
                while i < bytes.len() && bytes[i] != b'\n' { i += 1; }
            }
            b' ' | b'\t' | b'\n' | b'\r' => { i += 1; }
            b'(' => { out.push("(".into()); i += 1; }
            b')' => { out.push(")".into()); i += 1; }
            b'"' => {
                let start = i;
                i += 1;
                while i < bytes.len() && bytes[i] != b'"' { i += 1; }
                if i >= bytes.len() {
                    return Err(ImportError("unterminated string literal".into()));
                }
                i += 1;
                out.push(std::str::from_utf8(&bytes[start..i])
                    .map_err(|e| ImportError(format!("bad UTF-8 in string: {e}")))?
                    .to_string());
            }
            b'|' => {
                // Quoted symbol: |foo bar|
                let start = i;
                i += 1;
                while i < bytes.len() && bytes[i] != b'|' { i += 1; }
                if i >= bytes.len() {
                    return Err(ImportError("unterminated quoted symbol".into()));
                }
                i += 1;
                out.push(std::str::from_utf8(&bytes[start..i])
                    .map_err(|e| ImportError(format!("bad UTF-8 in symbol: {e}")))?
                    .to_string());
            }
            _ => {
                // Bare atom — runs until whitespace or `(` or `)` or `;`.
                let start = i;
                while i < bytes.len() {
                    let c = bytes[i];
                    if c.is_ascii_whitespace() || c == b'(' || c == b')' || c == b';' { break; }
                    i += 1;
                }
                out.push(std::str::from_utf8(&bytes[start..i])
                    .map_err(|e| ImportError(format!("bad UTF-8 in atom: {e}")))?
                    .to_string());
            }
        }
    }
    Ok(out)
}

fn parse_top_level(toks: &[String]) -> Result<Vec<Sexp>, ImportError> {
    let mut idx = 0;
    let mut out = Vec::new();
    while idx < toks.len() {
        out.push(parse_one(toks, &mut idx)?);
    }
    Ok(out)
}

fn parse_one(toks: &[String], idx: &mut usize) -> Result<Sexp, ImportError> {
    let tok = toks.get(*idx).ok_or_else(|| ImportError("unexpected EOF".into()))?;
    *idx += 1;
    match tok.as_str() {
        "(" => {
            let mut items = Vec::new();
            while *idx < toks.len() && toks[*idx] != ")" {
                items.push(parse_one(toks, idx)?);
            }
            if *idx >= toks.len() {
                return Err(ImportError("unmatched `(`".into()));
            }
            *idx += 1; // consume `)`
            Ok(Sexp::List(items))
        }
        ")" => Err(ImportError("unexpected `)`".into())),
        a => Ok(Sexp::Atom(a.to_string())),
    }
}

/// Translate one top-level form into a body item, or None if it's a
/// solver directive we ignore.
fn form_to_body_item(form: &Sexp) -> Result<Option<BodyItem>, ImportError> {
    let Sexp::List(items) = form else {
        return Err(ImportError(format!("expected list at top level, got atom")));
    };
    let head = items.first().ok_or_else(|| ImportError("empty top-level list".into()))?;
    let head_name = match head {
        Sexp::Atom(s) => s.as_str(),
        _ => return Err(ImportError("top-level form must start with an atom".into())),
    };
    match head_name {
        "declare-const" => {
            // (declare-const name sort)
            if items.len() != 3 {
                return Err(ImportError(format!(
                    "declare-const expects 2 args, got {}", items.len() - 1)));
            }
            let name = atom(&items[1])?.to_string();
            let sort = sort_to_evident(&items[2])?;
            Ok(Some(BodyItem::Membership {
                name, type_name: sort, pins: Pins::None,
            }))
        }
        "declare-fun" => {
            // (declare-fun name (args...) sort) — only zero-args supported.
            if items.len() != 4 {
                return Err(ImportError(format!(
                    "declare-fun expects 3 args, got {}", items.len() - 1)));
            }
            let name = atom(&items[1])?.to_string();
            let Sexp::List(args) = &items[2] else {
                return Err(ImportError("declare-fun arg list must be a list".into()));
            };
            if !args.is_empty() {
                return Err(ImportError(format!(
                    "declare-fun `{name}`: higher-arity functions not supported in v1 \
                     (got {} args). Encode as a relation via constraints.",
                    args.len()
                )));
            }
            let sort = sort_to_evident(&items[3])?;
            Ok(Some(BodyItem::Membership {
                name, type_name: sort, pins: Pins::None,
            }))
        }
        "assert" => {
            if items.len() != 2 {
                return Err(ImportError(format!(
                    "assert expects 1 arg, got {}", items.len() - 1)));
            }
            let e = sexp_to_expr(&items[1])?;
            Ok(Some(BodyItem::Constraint(e)))
        }
        "set-option" | "set-info" | "set-logic" |
        "check-sat" | "get-model" | "get-value" | "get-info" |
        "exit" | "push" | "pop" | "reset" | "echo" => {
            // Solver directive — silently dropped.
            Ok(None)
        }
        other => Err(ImportError(format!(
            "import: unsupported top-level form `{other}` — only declare-const, \
             declare-fun (zero-arg), and assert are in scope for v1"
        ))),
    }
}

fn atom<'a>(s: &'a Sexp) -> Result<&'a str, ImportError> {
    match s {
        Sexp::Atom(a) => Ok(a),
        _ => Err(ImportError("expected atom, got list".into())),
    }
}

fn sort_to_evident(s: &Sexp) -> Result<String, ImportError> {
    let n = atom(s).map_err(|_| ImportError(
        "compound sort (e.g. `(_ BitVec 32)`, `(Array …)`) not supported in v1".into()))?;
    match n {
        "Int" | "Real" | "Bool" | "String" => Ok(n.to_string()),
        other => Err(ImportError(format!(
            "import: sort `{other}` not in scope (supported: Int, Real, Bool, String)"
        ))),
    }
}

fn sexp_to_expr(s: &Sexp) -> Result<Expr, ImportError> {
    match s {
        Sexp::Atom(a) => atom_to_expr(a),
        Sexp::List(items) => {
            if items.is_empty() {
                return Err(ImportError("empty list in expression".into()));
            }
            let head = match &items[0] {
                Sexp::Atom(s) => s.as_str(),
                _ => return Err(ImportError("expression head must be atom".into())),
            };
            // n-ary operator handling.
            match head {
                "and" | "or" => {
                    let args: Vec<Expr> = items[1..].iter()
                        .map(sexp_to_expr).collect::<Result<_, _>>()?;
                    let op = if head == "and" { BinOp::And } else { BinOp::Or };
                    Ok(left_fold(op, args))
                }
                "+" | "-" | "*" => {
                    let args: Vec<Expr> = items[1..].iter()
                        .map(sexp_to_expr).collect::<Result<_, _>>()?;
                    if args.len() == 1 && head == "-" {
                        // Unary minus: SMT-LIB allows (- x). Evident
                        // doesn't have unary minus; desugar to 0 - x.
                        return Ok(Expr::Binary(
                            BinOp::Sub,
                            Box::new(Expr::Int(0)),
                            Box::new(args.into_iter().next().unwrap()),
                        ));
                    }
                    let op = match head {
                        "+" => BinOp::Add, "-" => BinOp::Sub, "*" => BinOp::Mul,
                        _ => unreachable!(),
                    };
                    Ok(left_fold(op, args))
                }
                "div" | "/" | "mod" => {
                    if items.len() != 3 {
                        return Err(ImportError(format!(
                            "{head} expects 2 args, got {}", items.len() - 1)));
                    }
                    let l = sexp_to_expr(&items[1])?;
                    let r = sexp_to_expr(&items[2])?;
                    let op = match head { "div" | "/" => BinOp::Div, "mod" => BinOp::Div, _ => unreachable!() };
                    Ok(Expr::Binary(op, Box::new(l), Box::new(r)))
                }
                "<" | "<=" | ">" | ">=" | "=" | "distinct" => {
                    if items.len() != 3 {
                        return Err(ImportError(format!(
                            "{head} expects 2 args in v1, got {}", items.len() - 1)));
                    }
                    let l = sexp_to_expr(&items[1])?;
                    let r = sexp_to_expr(&items[2])?;
                    let op = match head {
                        "<"  => BinOp::Lt,  "<=" => BinOp::Le,
                        ">"  => BinOp::Gt,  ">=" => BinOp::Ge,
                        "="  => BinOp::Eq,  "distinct" => BinOp::Neq,
                        _ => unreachable!(),
                    };
                    Ok(Expr::Binary(op, Box::new(l), Box::new(r)))
                }
                "=>" | "implies" => {
                    if items.len() != 3 {
                        return Err(ImportError(format!(
                            "=> expects 2 args, got {}", items.len() - 1)));
                    }
                    let l = sexp_to_expr(&items[1])?;
                    let r = sexp_to_expr(&items[2])?;
                    Ok(Expr::Binary(BinOp::Implies, Box::new(l), Box::new(r)))
                }
                "not" => {
                    if items.len() != 2 {
                        return Err(ImportError(format!(
                            "not expects 1 arg, got {}", items.len() - 1)));
                    }
                    Ok(Expr::Not(Box::new(sexp_to_expr(&items[1])?)))
                }
                "ite" => {
                    // SMT-LIB if-then-else; Evident has no ternary.
                    // Encode as (cond ⇒ a) ∧ (¬cond ⇒ b) — same
                    // semantics, just verbose. For Bool results
                    // it's clean; for non-Bool it's awkward but
                    // valid because Evident's `∧` is bool-typed,
                    // not value-typed. v1 punts on this if both
                    // branches aren't bool.
                    if items.len() != 4 {
                        return Err(ImportError("ite expects 3 args".into()));
                    }
                    let c = sexp_to_expr(&items[1])?;
                    let a = sexp_to_expr(&items[2])?;
                    let b = sexp_to_expr(&items[3])?;
                    let then_arm = Expr::Binary(BinOp::Implies,
                        Box::new(c.clone()), Box::new(a));
                    let else_arm = Expr::Binary(BinOp::Implies,
                        Box::new(Expr::Not(Box::new(c))), Box::new(b));
                    Ok(Expr::Binary(BinOp::And, Box::new(then_arm), Box::new(else_arm)))
                }
                "forall" | "exists" => sexp_to_quantifier(head, items),
                other => Err(ImportError(format!(
                    "import: unsupported operator `{other}`"))),
            }
        }
    }
}

fn atom_to_expr(a: &str) -> Result<Expr, ImportError> {
    if a == "true"  { return Ok(Expr::Bool(true)); }
    if a == "false" { return Ok(Expr::Bool(false)); }
    if let Ok(n) = a.parse::<i64>() { return Ok(Expr::Int(n)); }
    if let Ok(r) = a.parse::<f64>() {
        if a.contains('.') || a.contains('e') || a.contains('E') {
            return Ok(Expr::Real(r));
        }
    }
    if a.starts_with('"') && a.ends_with('"') {
        let inner = &a[1..a.len() - 1];
        return Ok(Expr::Str(inner.replace("\"\"", "\"")));
    }
    Ok(Expr::Identifier(a.to_string()))
}

fn left_fold(op: BinOp, args: Vec<Expr>) -> Expr {
    if args.is_empty() {
        // (and) = true, (or) = false, (+) = 0, (*) = 1, etc.
        return match op {
            BinOp::And => Expr::Bool(true),
            BinOp::Or  => Expr::Bool(false),
            BinOp::Add => Expr::Int(0),
            BinOp::Mul => Expr::Int(1),
            _ => Expr::Bool(true), // unreachable for valid input
        };
    }
    let mut iter = args.into_iter();
    let mut acc = iter.next().unwrap();
    for next in iter {
        acc = Expr::Binary(op.clone(), Box::new(acc), Box::new(next));
    }
    acc
}

fn sexp_to_quantifier(head: &str, items: &[Sexp]) -> Result<Expr, ImportError> {
    // (forall ((x Int) (y Int)) body) or (exists …)
    if items.len() != 3 {
        return Err(ImportError(format!(
            "{head} expects (binders body), got {} args", items.len() - 1)));
    }
    let Sexp::List(binder_pairs) = &items[1] else {
        return Err(ImportError(format!("{head}: binder list must be a list")));
    };
    if binder_pairs.len() != 1 {
        return Err(ImportError(format!(
            "{head}: only single-binder quantifiers supported in v1, got {}",
            binder_pairs.len()
        )));
    }
    let Sexp::List(bp) = &binder_pairs[0] else {
        return Err(ImportError(format!("{head}: each binder must be (var sort)")));
    };
    if bp.len() != 2 {
        return Err(ImportError(format!("{head}: binder must be (var sort) pair")));
    }
    let var = atom(&bp[0])?.to_string();
    let _sort = sort_to_evident(&bp[1])?;
    let body = sexp_to_expr(&items[2])?;

    // Evident requires bounded quantifiers `∀ x ∈ {lo..hi}`. Detect
    // the two patterns the exporter emits — `forall` uses
    // `(=> (and (>= var lo) (<= var hi)) inner)`, `exists` uses
    // `(and (>= var lo) (<= var hi) inner)` — and reverse them. Any
    // other shape is rejected (we don't have unbounded ranges).
    let (low, high, inner) = match (head, &body) {
        ("forall", Expr::Binary(BinOp::Implies, ant, cons)) => {
            extract_range_guard(&var, ant)
                .map(|(l, h)| (l, h, (**cons).clone()))
                .ok_or_else(|| ImportError(format!(
                    "import: forall over `{var}` lacks a recognizable \
                     `(>= {var} lo) ∧ (<= {var} hi)` antecedent — only \
                     bounded ranges are supported in v1"
                )))?
        }
        ("exists", Expr::Binary(BinOp::And, lhs, rhs)) => {
            // (and (>= var lo) (<= var hi) inner) parses left-fold
            // as ((and a b) c). Need to peel off the range guard
            // however the conjunction associates.
            extract_exists_range(&var, &Expr::Binary(BinOp::And, lhs.clone(), rhs.clone()))
                .ok_or_else(|| ImportError(format!(
                    "import: exists over `{var}` lacks a recognizable \
                     range guard — only bounded ranges are supported in v1"
                )))?
        }
        _ => return Err(ImportError(format!(
            "import: {head} body doesn't match the bounded-range shape \
             — only `(>= {var} lo) ∧ (<= {var} hi)` guards supported"
        ))),
    };

    let range = Expr::Range(Box::new(low), Box::new(high));
    Ok(match head {
        "forall" => Expr::Forall(vec![var], Box::new(range), Box::new(inner)),
        "exists" => Expr::Exists(vec![var], Box::new(range), Box::new(inner)),
        _ => unreachable!(),
    })
}

/// Match `(and (>= var LO) (<= var HI))` (or with sides swapped)
/// and extract `(LO, HI)`. Used for the forall antecedent.
fn extract_range_guard(var: &str, e: &Expr) -> Option<(Expr, Expr)> {
    let Expr::Binary(BinOp::And, lhs, rhs) = e else { return None };
    let lo = is_lower_bound(var, lhs).or_else(|| is_lower_bound(var, rhs))?;
    let hi = is_upper_bound(var, lhs).or_else(|| is_upper_bound(var, rhs))?;
    Some((lo, hi))
}

/// Match the exporter's exists shape: `(and guard_lo guard_hi inner)`
/// (left-folded into `((and lo hi) inner)` or `(and lo (and hi inner))`).
/// Returns `(lo, hi, inner)` if recognized, None otherwise.
fn extract_exists_range(var: &str, e: &Expr) -> Option<(Expr, Expr, Expr)> {
    // Try the left-folded shape: ((and (>= var lo) (<= var hi)) inner)
    if let Expr::Binary(BinOp::And, ll, rr) = e {
        if let Some((lo, hi)) = extract_range_guard(var, ll) {
            return Some((lo, hi, (**rr).clone()));
        }
        // Right-folded: (and (>= var lo) (and (<= var hi) inner))
        if let Some(lo) = is_lower_bound(var, ll) {
            if let Expr::Binary(BinOp::And, m, n) = rr.as_ref() {
                if let Some(hi) = is_upper_bound(var, m) {
                    return Some((lo, hi, (**n).clone()));
                }
            }
        }
    }
    None
}

/// `(>= var X)` → Some(X) if var matches, else None.
fn is_lower_bound(var: &str, e: &Expr) -> Option<Expr> {
    let Expr::Binary(BinOp::Ge, lhs, rhs) = e else { return None };
    if let Expr::Identifier(n) = lhs.as_ref() {
        if n == var { return Some((**rhs).clone()); }
    }
    None
}

/// `(<= var X)` → Some(X) if var matches, else None.
fn is_upper_bound(var: &str, e: &Expr) -> Option<Expr> {
    let Expr::Binary(BinOp::Le, lhs, rhs) = e else { return None };
    if let Expr::Identifier(n) = lhs.as_ref() {
        if n == var { return Some((**rhs).clone()); }
    }
    None
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/// Pretty-print a list of body items as Evident source. Used by the
/// import CLI to render the parsed SMT-LIB as a fresh `claim` block.
pub fn body_items_to_evident(name: &str, items: &[BodyItem]) -> String {
    let mut out = format!("claim {name}\n");
    for item in items {
        out.push_str("    ");
        out.push_str(&body_item_to_evident(item));
        out.push('\n');
    }
    out
}

fn body_item_to_evident(item: &BodyItem) -> String {
    match item {
        BodyItem::Membership { name, type_name, .. } => {
            format!("{name} ∈ {type_name}")
        }
        BodyItem::Constraint(e) => crate::pretty::expr(e),
        other => format!("/* unsupported on import: {other:?} */"),
    }
}
