#!/usr/bin/env python3
"""Render docs/perf/bottlenecks.md from the raw JSON emitted by
`evident profile <file> --all --json`.

Usage:
    python3 scripts/gen_bottlenecks.py <raw_dir> [--date YYYY-MM-DD]

`<raw_dir>` holds one `*.json` file per profiled source file, each the
verbatim stdout of one `evident profile … --all --json` invocation
(shape: `{"files": [{"file": ..., "claims": [...]}]}`). This script
merges them, ranks, and prints the markdown report to stdout.

Kept separate from `profile-all.sh` so the formatting can change without
re-running the (minutes-long) profiling sweep.
"""

import sys
import glob
import json
import os
import datetime


def load_runs(raw_dir):
    """Merge every raw JSON file into a flat list of (file, claims)."""
    runs = []
    for path in sorted(glob.glob(os.path.join(raw_dir, "*.json"))):
        try:
            with open(path) as fh:
                doc = json.load(fh)
        except (json.JSONDecodeError, OSError) as e:
            sys.stderr.write(f"  warn: skipping unreadable {path}: {e}\n")
            continue
        for entry in doc.get("files", []):
            runs.append(entry)
    return runs


def fmt_us(n):
    """123456 -> '123,456'. None -> '—'."""
    if n is None:
        return "—"
    return f"{int(n):,}"


def fmt_delta(d):
    return "—" if d is None else f"{int(d):,}"


def all_claims(runs):
    """Yield (file, claim) for every profiled claim across all files."""
    for entry in runs:
        f = entry["file"]
        for c in entry.get("claims", []):
            yield f, c


def top_bottleneck(claim):
    """The highest-savings bottleneck row, or None."""
    bs = claim.get("bottlenecks") or []
    return bs[0] if bs else None


def write_header(out, date):
    out.append("# Bottleneck report — stdlib + examples")
    out.append("")
    out.append(f"> Generated by `scripts/profile-all.sh` on {date}. "
               "**Do not edit by hand** — re-run the driver to refresh.")
    out.append("")
    out.append("## How to read this report")
    out.append("")
    out.append(
        "Every queryable schema in `examples/` and `stdlib/` is profiled with "
        "[`evident profile`](../../runtime/src/commands/profile.rs). For each "
        "claim the tool:")
    out.append("")
    out.append(
        "1. **Solves it once, cold** (translate → build solver → Z3 `check()` "
        "→ extract a model) and times the whole thing. That wall-clock is the "
        "claim's **baseline solve cost** — column *baseline solve (μs)* below. "
        "The sweep runs with `EVIDENT_FUNCTIONIZE=0`, so this is the **pure "
        "Z3 cost**: exactly the work the JIT / native-codegen path aims to "
        "replace.")
    out.append("")
    out.append(
        "2. **Ranks the solved-for variables by pin-savings.** It pins each "
        "scalar (`Int`/`Bool`/`String`) leaf the baseline model produced to "
        "that value and re-solves. *savings(μs)* = `baseline − pinned`: how "
        "much faster the solve gets when a caller (or an upstream FSM) "
        "supplies that variable instead of leaving Z3 to derive it. A large "
        "positive savings means **that variable is a bottleneck** — feeding it "
        "in, caching it, or compiling its derivation would pay off most. "
        "`Δconflicts` / `Δdecisions` are the matching drops in Z3 search "
        "effort (`baseline − pinned`); they corroborate *why* the pin helped.")
    out.append("")
    out.append(
        "**Caveats.** Times are single-run, warm-process microsecond solves on "
        "one machine — treat them as *relative* signal, not absolute "
        "benchmarks. Small claims sit near solver-overhead noise (±a few "
        "hundred μs); a negative savings just means the pin cost more than it "
        "saved at that scale. Claims marked **no scalar candidates** solve for "
        "only enum / sequence / record values (e.g. an FSM whose outputs are "
        "`state_next` + `Seq(Effect)`); the v1 pin-finder only pins scalars, "
        "so there's no per-variable table — the baseline solve cost is still "
        "reported. `unsat` / `error` claims couldn't produce a satisfiable "
        "baseline standalone (often they need scheduler-level pins) and are "
        "listed for completeness.")
    out.append("")


def write_global_ranking(out, runs):
    rows = []
    for f, c in all_claims(runs):
        if c.get("query_us") is None:
            continue
        tb = top_bottleneck(c)
        rows.append({
            "claim": c["schema"],
            "file": f,
            "baseline": c["query_us"],
            "status": c["status"],
            "top_var": tb["var"] if tb else "—",
            "top_sav": tb["savings_us"] if tb else None,
        })
    rows.sort(key=lambda r: r["baseline"], reverse=True)

    out.append("## Global ranking — most expensive claims")
    out.append("")
    out.append(
        "Ranked by total baseline solve cost. These are the hot spots: the "
        "claims where the runtime spends the most Z3 time, and therefore the "
        "highest-value targets for JIT / native-codegen work.")
    out.append("")
    out.append("| rank | claim | file | baseline solve (μs) | top pin-var | top savings (μs) |")
    out.append("|---:|---|---|---:|---|---:|")
    for i, r in enumerate(rows, 1):
        out.append(
            f"| {i} | `{r['claim']}` | `{r['file']}` | {fmt_us(r['baseline'])} "
            f"| `{r['top_var']}` | {fmt_us(r['top_sav']) if r['top_sav'] is not None else '—'} |")
    out.append("")


def write_savings_ranking(out, runs, limit=25):
    rows = []
    for f, c in all_claims(runs):
        tb = top_bottleneck(c)
        if tb is None:
            continue
        rows.append({
            "claim": c["schema"],
            "file": f,
            "var": tb["var"],
            "savings": tb["savings_us"],
            "baseline": tb["baseline_us"],
            "pinned": tb["pinned_us"],
        })
    rows.sort(key=lambda r: r["savings"], reverse=True)
    rows = rows[:limit]

    out.append("## Biggest single-variable wins")
    out.append("")
    out.append(
        f"Top {limit} variables across the whole codebase by pin-savings — the "
        "individual constraints whose derivation costs Z3 the most. Supplying "
        "or precomputing one of these is the most direct per-variable "
        "optimization.")
    out.append("")
    out.append("| rank | variable | claim | file | savings (μs) | baseline → pinned (μs) |")
    out.append("|---:|---|---|---|---:|---:|")
    for i, r in enumerate(rows, 1):
        out.append(
            f"| {i} | `{r['var']}` | `{r['claim']}` | `{r['file']}` "
            f"| {fmt_us(r['savings'])} | {fmt_us(r['baseline'])} → {fmt_us(r['pinned'])} |")
    out.append("")


def write_per_file(out, runs):
    out.append("## Per-file detail")
    out.append("")
    for entry in sorted(runs, key=lambda e: e["file"]):
        f = entry["file"]
        claims = entry.get("claims", [])
        out.append(f"### `{f}`")
        out.append("")
        if not claims:
            out.append("_No queryable schemas (all generic templates, "
                       "test claims, or enum-only)._")
            out.append("")
            continue
        for c in claims:
            status = c["status"]
            qus = fmt_us(c.get("query_us"))
            label = {
                "ok": f"baseline {qus} μs",
                "no_candidates": f"baseline {qus} μs · no scalar candidates",
                "unsat": "UNSAT standalone",
                "error": "error",
            }.get(status, status)
            out.append(f"#### `{c['schema']}` — {label}")
            out.append("")
            if c.get("message"):
                out.append(f"> {c['message']}")
                out.append("")
            bs = c.get("bottlenecks") or []
            if bs:
                out.append("| rank | variable | baseline(μs) | pinned(μs) "
                           "| savings(μs) | Δconflicts | Δdecisions |")
                out.append("|---:|---|---:|---:|---:|---:|---:|")
                for b in bs:
                    out.append(
                        f"| {b['rank']} | `{b['var']}` | {fmt_us(b['baseline_us'])} "
                        f"| {fmt_us(b['pinned_us'])} | {fmt_us(b['savings_us'])} "
                        f"| {fmt_delta(b.get('conflicts_delta'))} "
                        f"| {fmt_delta(b.get('decisions_delta'))} |")
                out.append("")
            elif status == "no_candidates":
                gv = ", ".join(f"`{v}`" for v in c.get("solved_for", [])) or "—"
                out.append(f"Solves for (non-scalar): {gv}")
                out.append("")
    return


def summary_line(runs):
    n_files = len(runs)
    n_claims = sum(len(e.get("claims", [])) for e in runs)
    n_ok = sum(1 for _, c in all_claims(runs) if c["status"] == "ok")
    return (f"Covered **{n_files} files**, **{n_claims} queryable schemas** "
            f"({n_ok} with scalar bottleneck data).")


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: gen_bottlenecks.py <raw_dir> [--date YYYY-MM-DD]\n")
        return 2
    raw_dir = sys.argv[1]
    date = datetime.date.today().isoformat()
    if "--date" in sys.argv:
        date = sys.argv[sys.argv.index("--date") + 1]

    runs = load_runs(raw_dir)
    if not runs:
        sys.stderr.write(f"no profile JSON found in {raw_dir}\n")
        return 1

    out = []
    write_header(out, date)
    out.append(summary_line(runs))
    out.append("")
    write_global_ranking(out, runs)
    write_savings_ranking(out, runs)
    write_per_file(out, runs)
    out.append("---")
    out.append("")
    out.append("_Regenerate with `./scripts/profile-all.sh`._")
    out.append("")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
